language: node_js
node_js:
  - "0.11"
  - "0.10"
install: cd impl; npm install;
before_script:
  - sleep 15
  - mongo improveyourvocabulary --eval 'db.addUser("admin", "4nVL27YyApru");'
script: cd impl/; npm test;
services:
  - mongodb
